-- `actualizaciones_precio_items.variante_id` pierde su FK: el historial de
-- precios tiene que sobrevivir a que la variante desaparezca.
--
-- QUÉ HACÍA MAL. La FK era ON DELETE SET NULL, así que borrar una variante le
-- escribía null encima al id en sus filas de historial. Sin dejar rastro de
-- cuál era: el dato no se degrada, se borra.
--
-- CUÁNTO, MEDIDO BIEN. La tabla tiene 6.122 filas y 2.517 con `variante_id` en
-- null, pero **la mayoría de esos nulls son por diseño, no pérdida**:
-- `aplicarPreciosAction` escribe UNA fila de nivel PRODUCTO (con variante_id
-- null a propósito) más una por cada variante. Comparando nulls contra
-- productos distintos por lote, los cinco lotes del 11/7 tienen exactamente
-- uno por producto —cero de más— y los cinco siguientes tienen 14, 135, 135,
-- 144 y 161 de más.
--
--   1.928 nulls  -> la fila de nivel producto, correcta
--     589 nulls  -> historial de variante que el SET NULL destruyó
--
-- No son recuperables: no queda de dónde mapear el id. Lo que se arregla acá
-- es que deje de pasar.
--
-- Y ADEMÁS ARREGLA UN BUG LATENTE, que es el motivo más fuerte. `revertirLote`
-- decide qué hacer mirando si `variante_id` es null:
--
--   con id   -> revierte esa variante puntual
--   sin id   -> revierte `productos.precio` a `precio_anterior` de la fila
--
-- Cuando el SET NULL convierte la fila de una variante borrada en un null, esa
-- fila pasa a la rama de nivel producto y **pisa el precio del producto con el
-- precio viejo de una variante**. Medido: 66 productos donde revertir hoy
-- escribiría un precio equivocado. Nunca se disparó porque los 10 lotes están
-- en APLICADO y ninguno se revirtió, pero el botón está en la UI.
--
-- Con el id conservado, esa fila toma la rama por-variante y hace un UPDATE
-- que afecta 0 filas — que es lo correcto: la variante no existe, no hay
-- precio que restaurarle. Y la fila de nivel producto sigue siendo una sola.
--
-- POR QUÉ SIN FK Y NO RESTRICT. RESTRICT bloquearía borrar cualquiera de las
-- 1.030 variantes que hoy tienen historial de precios (el 18% del catálogo).
-- No poder dar de baja un talle porque alguna vez se le corrió un ajuste de
-- precios es un costo desproporcionado para proteger un registro histórico.
--
-- Sin FK es el patrón que este repo ya usa para exactamente esto, y está
-- documentado en los dos lugares: `ventas_items.variante_id` ("Sin FK: el
-- historial sobrevive a que la variante se borre", 20260816130000) y
-- `producto_variantes_auditoria` ("SIN FK dura — debe sobrevivir a la
-- desaparición del original", 20260719160000). Un id colgado es más útil que
-- un null: se puede comparar, agrupar y —desde 20260902130000— resolver contra
-- `variantes_remapeo`.
--
-- La contracara, dicha de frente: sin FK la base ya no garantiza que el id
-- apunte a algo. Es la misma decisión, con el mismo precio, que ya se tomó en
-- las otras dos tablas de historial.
--
-- REVERSIBLE: volver a poner la FK es un statement, pero ver el `_down` antes
-- de correrlo.

alter table public.actualizaciones_precio_items
  drop constraint actualizaciones_precio_items_variante_id_fkey;

comment on column public.actualizaciones_precio_items.variante_id is
  'Variante a la que corresponde esta fila de historial, o NULL cuando la fila es de nivel PRODUCTO (aplicarPreciosAction escribe una por producto además de una por variante). SIN FK a propósito desde 20260902190000: el historial tiene que sobrevivir a que la variante se borre, y el ON DELETE SET NULL anterior no solo perdía el dato sino que hacía que revertir el lote pisara el precio del producto. Un id que ya no existe se puede resolver contra variantes_remapeo.';
