-- Saca `productos.cuidados`, que nunca fue una columna de este proyecto.
--
-- Viene del esquema original (20260101000000_esquema_maestro.sql), de cuando
-- esto era una tienda de plantas: `cuidados text DEFAULT 'Luz indirecta'`.
-- Ninguna pantalla la escribe y ninguna la muestra — ni la ficha de producto,
-- que es la única que mostraría algo así.
--
-- Verificado en producción antes de escribir esta migración, sobre los 4
-- negocios juntos:
--
--   total productos ........................ 1.806
--   con `cuidados` no nulo ................. 1.806
--   con el valor 'Luz indirecta' ........... 1.806
--   con cualquier otro contenido ...........     0
--   valores distintos en la columna ........     1
--
-- O sea: no hay un solo dato que perder. Todas las filas tienen el default que
-- puso la columna al crearse.
--
-- ORDEN DE APLICACIÓN (importa, y es la regla de las 3 patas del CLAUDE.md):
-- esta migración va DESPUÉS de deployar el código que deja de pedir la
-- columna. `COLUMNAS_PRODUCTO_PUBLICO` la pedía, y la usan la ficha de
-- producto y el catálogo del POS: aplicar esto contra el código viejo convierte
-- esos dos `select` en un 400 para los 4 negocios a la vez.
--
-- El GRANT de SELECT que anon tenía sobre la columna
-- (20260811140000_rls_anon_catalogo_publico.sql) se va solo con el DROP: los
-- privilegios por columna no sobreviven a la columna.

alter table public.productos drop column if exists cuidados;
