-- Índice en producto_variantes(producto_id): la FK más caliente del sistema y
-- la única que no tenía índice.
--
-- Por qué: TODA pantalla que lista productos pide sus variantes en el mismo
-- viaje (`producto_variantes(...)` como embed de PostgREST) — el catálogo
-- público, la terminal del POS y /stock. Sin índice sobre la columna del join,
-- Postgres resuelve cada embed con un SEQ SCAN de la tabla entera, una vez por
-- producto.
--
-- Medido en producción (12/8/2026), listando los 1.116 productos de Evens:
--
--   Seq Scan on producto_variantes  (rows=3  loops=1116)
--         Filter: (producto_id = p.id)
--         Rows Removed by Filter: 4910      <- por CADA producto
--   Buffers: shared hit=181997
--   Execution Time: 833.944 ms
--
-- O sea ~5,5 millones de comparaciones de fila para devolver 2.965 variantes.
-- La misma consulta con un camino de acceso indexado corre en 7,15 ms: 116x.
--
-- Se descubrió auditando por qué faltaban productos en el catálogo (el tope de
-- 1000 filas de PostgREST, ver shared/lib/traer-todo.ts). No es la misma causa,
-- pero es el mismo tipo de problema: algo que degrada en silencio y solo se
-- nota cuando el negocio creció lo suficiente. Evens tiene 2.965 variantes
-- propias y la tabla 4.913 en total; el costo del seq scan crece con la tabla
-- COMPARTIDA, así que cada negocio nuevo lo empeora para todos.
--
-- La columna sola alcanza: el filtro por `negocio_id` de la RLS ya tiene su
-- propio índice, y la búsqueda del embed siempre entra por producto_id.
--
-- Sin CONCURRENTLY a propósito: no puede correr dentro de una transacción, y
-- acá no hace falta — la tabla son 1.928 kB / 4.913 filas, así que el índice se
-- construye en milisegundos y el lock de escritura es despreciable. Con una
-- tabla grande esta decisión sería la contraria.
--
-- Aditiva y reversible: `drop index if exists idx_producto_variantes_producto_id;`

create index if not exists idx_producto_variantes_producto_id
  on public.producto_variantes using btree (producto_id);
